export const SIDEBAR_MENU_ITEMS = [
  {
    id: "home",
    label: "Home",
    labelKey: "navigation.home",
    path: "/crm/tasks-v1/home",
    hasChevron: false,
  },
  {
    id: "risk-management",
    label: "CRM Suite",
    labelKey: "navigation.riskManagement",
    path: "/crm/tasks-v1/risk-management",
    hasChevron: false,
  },
  {
    id: "clients",
    label: "Clients",
    labelKey: "navigation.clients",
    path: null,
    hasChevron: true,
  },
  {
    id: "users",
    label: "Users",
    labelKey: "navigation.users",
    path: null,
    hasChevron: true,
  },
  {
    id: "financial",
    label: "Financial",
    labelKey: "navigation.financial",
    path: null,
    hasChevron: true,
  },
  {
    id: "accounts-emails",
    label: "Accounts & Emails",
    labelKey: "navigation.accountsAndEmails",
    path: null,
    hasChevron: true,
  },
  {
    id: "ib",
    label: "IB",
    labelKey: "navigation.ib",
    path: null,
    hasChevron: true,
  },
  {
    id: "chat",
    label: "Chat",
    labelKey: "navigation.chat",
    path: null,
    hasChevron: true,
  },
  {
    id: "logout",
    label: "Log Out",
    labelKey: "navigation.logout",
    path: null,
    hasChevron: false,
  },
];
